version: '3.8'

services:
  janus:
    # Используем ОФИЦИАЛЬНЫЙ образ от Meetecho
    image: canyan/janus-gateway:latest
    container_name: janus_official
    restart: always
    
    ports:
      - "8088:8088"       # HTTP REST API
      - "8188:8188"       # WebSockets API (для клиентов)
      - "10000-10200:10000-10200/udp" # RTP медиа-порты для WebRTC

    # Эта строка критически важна для Linux! Она позволяет контейнеру 
    # обращаться к твоей хостовой машине по имени host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      # В официальном образе конфиги лежат в /opt/janus/etc/janus
      - ./conf:/usr/local/etc/janus
      #- "./certs:/etc/janus/certs:ro"
      - ../certs:/etc/janus/certs:ro
      #- ${FAKE_CERT:-/etc/letsencrypt/live/chatikon.ru}:/etc/janus/certs:ro
