version:  '3.8'
services:
  janus-gateway: 
    image:  'sucwangsr/janus-webrtc-gateway-docker:latest'
    container_name:  janus-gateway
    command: ["/usr/local/bin/janus", "-F","/usr/local/etc/janus"]
    #command: ["sh","-c","mkdir -p /opt/janus/lib/janus/plugins &&  ln -sf /usr/local/lib/janus/plugins/* /opt/janus/lib/janus/plugins/ 2>/dev/null || true && /usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    network_mode: "host"
    volumes:
      - "./conf/janus.transport.websockets.jcfg:/usr/local/etc/janus/janus.transport.websockets.jcfg"
      - "./conf/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
      - "./conf/janus.eventhandler.sampleevh.jcfg:/usr/local/etc/janus/janus.eventhandler.sampleevh.jcfg"
      - "./conf/janus.plugin.videoroom.jcfg:/usr/local/etc/janus/janus.plugin.videoroom.jcfg"
      - "./conf/janus.plugin.streaming.jcfg:/usr/local/etc/janus/janus.plugin.streaming.jcfg"
      - "./conf/janus.transport.http.jcfg:/usr/local/etc/janus/jansus.transport.http.jgfg"
      #- "./janus-plugins:/opt/janus/lib/janus/plugins:ro"
    #ports:
    #  - "5.35.88.151:8188:8188"
    
    restart: always
#sudo docker run --rm -v $(pwd)/janus-plugins:/target sucwangsr/janus-webrtc-gateway-docker:latest cp -r /usr/local/lib/janus/plugins/ /target/
