# /snap/bin/curl -v --http3 https://chatikon.ru
# caddy version
# v2.11.4 h1:XKxkMTgNSizEvKG6QHue6cAsFOteU2qA61w2tKkCWi0=
# sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https curl

# 3. Добавьте GPG ключ
# curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg

# 4. Добавьте репозиторий
# curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list

# 5. Установите
# sudo apt update
#sudo apt install caddy

# 6. Проверьте
# caddy version
sudo chown caddy:caddy /etc/letsencrypt/live/chatikon.ru/fullchain.pem
sudo chown caddy:caddy /etc/letsencrypt/live/chatikon.ru/privkey.pem
sudo chmod 644 /etc/letsencrypt/live/chatikon.ru/fullchain.pem
sudo chmod 640 /etc/letsencrypt/live/chatikon.ru/privkey.pem

sudo mkdir -p /etc/ssl/caddy
sudo cp /etc/letsencrypt/live/chatikon.ru/fullchain.pem /etc/ssl/caddy/ \
sudo cp /etc/letsencrypt/live/chatikon.ru/privkey.pem /etc/ssl/caddy/

# Установите права
sudo chown caddy:caddy /etc/ssl/caddy/*.pem
sudo chmod 644 /etc/ssl/caddy/fullchain.pem
sudo chmod 640 /etc/ssl/caddy/privkey.pem
rm /etc/ssl/caddy/*.pem
chatikon.ru {
    tls /etc/letsencrypt/live/chatikon.ru/fullchain.pem /etc/letsencrypt/live/chatikon.ru/privkey.pem {
        protocols tls1.2 tls1.3
    }

    # PeerJS на /peerjs (как в сервере)
    handle /peerjs/* {
        reverse_proxy chatikon.ru:9000 {
            header_up Host {host}
            header_up X-Real-IP {remote_host}
            header_up X-Forwarded-For {remote_host}
            header_up X-Forwarded-Proto {scheme}
            header_up Upgrade {http.request.header.Upgrade}
            header_up Connection {http.request.header.Connection}
            flush_interval -1
        }
    }

    # PeerJS на /peer (как в клиенте)  
    handle /peer/* {
        reverse_proxy chatikon.ru:9000 {
            header_up Host {host}
            header_up X-Real-IP {remote_host}
            header_up X-Forwarded-For {remote_host}
            header_up X-Forwarded-Proto {scheme}
            header_up Upgrade {http.request.header.Upgrade}
            header_up Connection {http.request.header.Connection}
            flush_interval -1
        }
    }

    # Express основной
    handle {
        reverse_proxy chatikon.ru:3000 {
            header_up Host {host}
            header_up X-Real-IP {remote_host}
            header_up X-Forwarded-For {remote_host}
            header_up X-Forwarded-Proto {scheme}
            header_up Upgrade {http.request.header.Upgrade}
            header_up Connection {http.request.header.Connection}
            flush_interval -1
        }
    }
}

